spring.application.name=demo

spring.datasource.url=jdbc:postgres://pandastack:2I1lAxQHTNEi0Nf9l1X5qn5FrHiQUeJRRPEfq78tPPix@298d9df7-8023-449d-a4c3-6f769668f70d.db.pandastack.ai:5432/pandastack
spring.ddatasource.username=pandastack
spring.datasource.password=2I1lAxQHTNEi0Nf9l1X5qn5FrHiQUeJRRPEfq78tPPix
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect